[author]
name = "Aravind Reddy Voggu"
email = "aravind.reddy@iiitb.org"
website = "https://www.avoggu.com/"

[nexmon_csi]
repository = "https://github.com/seemoo-lab/nexmon_csi.git"
branch = "master"

[nexmon]
repository = "https://github.com/seemoo-lab/nexmon.git"
branch = "master"

[[contents]]

[contents."5.10.92-v7l+"]
hashtype = "sha256"
hash = "1cffbe242d8f36b3c6e143d073ac811609830ad1002b2e4db68f25eace414ae9"
url = "https://github.com/nexmonster/nexmon_csi_bin/raw/main/base/5.10.92-v7l%2B.tar.xz"

[contents."5.10.92-v7+"]
hashtype = "sha256"
hash = "96202320710792db33c1b5e51436abcee30d40d0f47e9d6c53b647f4ba5035eb"
url = "https://github.com/nexmonster/nexmon_csi_bin/raw/main/base/5.10.92-v7%2B.tar.xz"